import 'package:flutter/material.dart';
import 'package:google_fonts/google_fonts.dart';

TextStyle myTextStyle = GoogleFonts.quicksand(
  color: Colors.white,
  fontWeight: FontWeight.bold,
  letterSpacing: 2,
);

late String contributionId = "";

late String fcmId = "";

late BuildContext globalContext;

late bool online = false;

final Map<int, Color> color = {
  50: const Color.fromRGBO(70, 161, 134, .1),
  100: const Color.fromRGBO(70, 161, 134, .2),
  200: const Color.fromRGBO(70, 161, 134, .3),
  300: const Color.fromRGBO(70, 161, 134, .4),
  400: const Color.fromRGBO(70, 161, 134, .5),
  500: const Color.fromRGBO(70, 161, 134, .6),
  600: const Color.fromRGBO(70, 161, 134, .7),
  700: const Color.fromRGBO(70, 161, 134, .8),
  800: const Color.fromRGBO(70, 161, 134, .9),
  900: const Color.fromRGBO(70, 161, 134, 1),
};

late List<String> cities = [
  "Karachi",
  "Lahore",
  "Faisalabad",
  "Rawalpindi",
  "Gujranwala",
  "Peshawar",
  "Multan",
  "Saidu Sharif",
  "Hyderabad City",
  "Islamabad",
  "Quetta",
  "Bahawalpur",
  "Sargodha",
  "Sialkot City",
  "Sukkur",
  "Larkana",
  "Chiniot",
  "Shekhupura",
  "Jhang City",
  "Dera Ghazi Khan",
  "Gujrat",
  "Rahimyar Khan",
  "Kasur",
  "Mardan",
  "Mingaora",
  "Nawabshah",
  "Sahiwal",
  "Mirpur Khas",
  "Okara",
  "Mandi Burewala",
  "Jacobabad",
  "Saddiqabad",
  "Kohat",
  "Muridke",
  "Muzaffargarh",
  "Khanpur",
  "Gojra",
  "Mandi Bahauddin",
  "Abbottabad",
  "Turbat",
  "Dadu",
  "Bahawalnagar",
  "Khuzdar",
  "Pakpattan",
  "Tando Allahyar",
  "Ahmadpur East",
  "Vihari",
  "Jaranwala",
  "New Mirpur",
  "Kamalia",
  "Kot Addu",
  "Nowshera",
  "Swabi",
  "Khushab",
  "Dera Ismail Khan",
  "Chaman",
  "Charsadda",
  "Kandhkot",
  "Chishtian",
  "Hasilpur",
  "Attock Khurd",
  "Muzaffarabad",
  "Mianwali",
  "Jalalpur Jattan",
  "Bhakkar",
  "Zhob",
  "Dipalpur",
  "Kharian",
  "Mian Channun",
  "Bhalwal",
  "Jamshoro",
  "Pattoki",
  "Harunabad",
  "Kahror Pakka",
  "Toba Tek Singh",
  "Samundri",
  "Shakargarh",
  "Sambrial",
  "Shujaabad",
  "Hujra Shah Muqim",
  "Kabirwala",
  "Mansehra",
  "Lala Musa",
  "Chunian",
  "Nankana Sahib",
  "Bannu",
  "Pasrur",
  "Timargara",
  "Parachinar",
  "Chenab Nagar",
  "Gwadar",
  "Abdul Hakim",
  "Hassan Abdal",
  "Tank",
  "Hangu",
  "Risalpur Cantonment",
  "Karak",
  "Kundian",
  "Umarkot",
  "Chitral",
  "Dainyor",
  "Kulachi",
  "Kalat",
  "Kotli",
  "Gilgit",
  "Narowal",
  "Khairpur Mir’s",
  "Khanewal",
  "Jhelum",
  "Haripur",
  "Shikarpur",
  "Rawala Kot",
  "Hafizabad",
  "Lodhran",
  "Malakand",
  "Attock City",
  "Batgram",
  "Matiari",
  "Ghotki",
  "Naushahro Firoz",
  "Alpurai",
  "Bagh",
  "Daggar",
  "Leiah",
  "Tando Muhammad Khan",
  "Chakwal",
  "Badin",
  "Lakki",
  "Rajanpur",
  "Dera Allahyar",
  "Shahdad Kot",
  "Pishin",
  "Sanghar",
  "Upper Dir",
  "Thatta",
  "Dera Murad Jamali",
  "Kohlu",
  "Mastung",
  "Dasu",
  "Athmuqam",
  "Loralai",
  "Barkhan",
  "Musa Khel Bazar",
  "Ziarat",
  "Gandava",
  "Sibi",
  "Dera Bugti",
  "Eidgah",
  "Uthal",
  "Khuzdar",
  "Chilas",
  "Panjgur",
  "Gakuch",
  "Qila Saifullah",
  "Kharan",
  "Aliabad",
  "Awaran",
  "Dalbandin"
];
